spring:
  datasource:
    url: ${db_url}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false